version: "3.8"

services:
  test:
    build: ./test
    networks: 
      - default
    links:
      - service1
      - service2

  service1:
    build: ./service1
    ports:
      - "8080:8080"
    networks:
      - default
  
  service2:
    build: ./service2
    ports:
      - "8081:8080"
    networks:
      - default

networks:
  default:
    name: avl