version: "3.8"

services:
  service1:
    build: ./service1
    ports:
      - "8080:8080"
    networks:
      - default
    image: tinzeljar/service1
  
  service2:
    build: ./service2
    ports:
      - "8081:8080"
    networks:
      - default
    image: tinzeljar/service2

networks:
  default:
    name: avl