name: Test, Build, Deploy

on:
  push:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: docker-compose -f docker-compose.test.yml build

    - name: Run test
      run: docker-compose -f docker-compose.test.yml run test
