name: Sending docker image to docker hub

on:
  push:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Stack
      run: docker-compose up -d
    
    - name: Test service 1
      run: curl -d "md5" localhost:8080
        
    - name: Test service 2
      run: curl -d "test" localhost:8081
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push
      run: docker-compose push
