name: Sending docker image to docker hub

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Stack
      run: docker-compose up -d
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test service 1
        run: curl -d "md5" localhost:8080
        
      - name: Test service 2
        run: curl -d "test" localhost:8081
  
  push:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Push
        run: docker-compose push
